aides_projets/Exemple_structure_arborescance_blueprint/routes/__init__.py
# le fichier __init__.py permet l'import des fichiers contenus dans le dossier routes.
# on y indique les emplacements des fichiers que contient le dossier routes


from flask import Blueprint
routes = Blueprint('routes', __name__)

from .index import *
from .acar1.acar1 import *
from .acar2.acar2 import *
from .acar1.page1 import *
from .acar1.page2 import *

aides_projets/Exemple_structure_arborescance_blueprint/routes/index.py
from flask import Flask, render_template, request, redirect, url_for, session,flash
from . import routes


@routes.route("/")
def index():
    return render_template("index.html")

aides_projets/Exemple_structure_arborescance_blueprint/templates/acar1/acar1.html
{% extends 'base.html' %}

{% block content %}

<h1>{% block title %} ACAR1 {% endblock %}</h1>
<a href="{{ url_for('routes.f_acar1_1') }}">Page1</a>
<a href="{{ url_for('routes.f_acar1_2') }}">Page1</a>



{% endblock %}

aides_projets/Exemple_structure_arborescance_blueprint/templates/acar1/page1.html
{% extends 'base.html' %}

{% block content %}

<h1>{% block title %} ACAR1 page1 {% endblock %}</h1>
<a href="{{ url_for('routes.f_acar1') }}">Acar1</a>

{% endblock %}

aides_projets/Exemple_structure_arborescance_blueprint/templates/acar1/page2.html
{% extends 'base.html' %}

{% block content %}

<h1>{% block title %} ACAR1 page2  {% endblock %}</h1>
<a href="{{ url_for('routes.f_acar1') }}">Acar1</a>

{% endblock %}

aides_projets/Exemple_structure_arborescance_blueprint/templates/acar2/acar2.html
{% extends "base.html" %}

{% block content %}

<h3>{% block title %} ACAR2 {% endblock %}</h3>

    
{% endblock %}

aides_projets/Exemple_structure_arborescance_blueprint/templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mon appli</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    {% block css %}{% endblock %}
</head>
<body>
    <nav id="navbar">
        <img src="{{ url_for('static', filename='img/logo.png') }}" alt="logo" width="50">
        <ul id="navbar-items">
            <li class="navbar-item">
                <a href="{{ url_for('routes.index') }}">Accueil</a>
            </li>
            
            
            <li class="navbar-item">
                <a href="{{ url_for('routes.f_acar1') }}">Acar1</a>
            </li>
           
            <li class="navbar-item">
                <a href="{{ url_for('routes.f_acar2') }}">Acar2</a>
            </li>
        </ul> 
    </nav>
    
    <div id="container">
        {% block content %}{% endblock %}
    </div>
    
</body>
</html>

aides_projets/Exemple_structure_arborescance_blueprint/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>Accueil</h1>
<p> bienvenue sur ACAR !</p>
{% endblock %}